### ISSUE TITLE
Why not start this project up again?

### ISSUE THREAD

**Issue by ghost** [ironbane/ironbane#5]
This project has gone open source. and I read in this issue https://github.com/ironbane/ironbane/issues/1 that It costs too much money to run it. I'll run it for free. We really should keep a project like this going.

**Comment by bsparks** [comment]
Well, there may be some who are open to working on the project, depending on your goals, etc. (I am one of them) I suggest to join what is left of us here and talk about it: https://discord.gg/RVphzYC (limit to 5 uses in case of bots, if someone else wants more just ask).

**Comment by Khroft** [comment]
Ive got a measure of 3d modelling and design experience i could probably help if it started up again

**Comment by bsparks** [comment]
@alwaysontop617 you are free to do that, since it's open source. However, for the record, what you actually did was ask to buy the domain and when told no threw a tantrum and spammed the server with nonsense.
